name: LlamaEconomy
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
main: me.petterim1.llamabridge.Loader
description: Run plugins that depend on LlamaEconomy with EconomyAPI
depend: ["EconomyAPI"]
